version: '3'

services:
  django:
    build: .
    ports:
      - "8020:8080"
  django2:
    build: .
    ports:
      - "8021:8080"
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8080:80"
    depends_on:
      - django
      - django2